name: Deploy School Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  
      
      - name: Create env file
        run: touch .env

      - name: Assign value to .env
        run: echo "${{ secrets.PROD_ENV_FILE }}" > .env

      - name: Build Docker Image
        run: docker build -t yuttana76/school-app .

      - name: Publish Image to docker hub
        run: docker push yuttana76/school-app:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull yuttana76/school-app:latest 
      - name: Delete old container
        run: docker rm -f school-app
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name school-app yuttana76/school-app